# Generated by Django 5.1.4 on 2025-01-12 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='value',
            field=models.BooleanField(default=True, verbose_name='Значение'),
        ),
    ]
